global:
  scrape_interval: 15s

scrape_configs:
  # FastApi 애플리케이션의 메트릭 수집
  - job_name: 'fastapi'
    static_configs:
      - targets: ['fastapi-app:8005']  # Docker 네트워크에서는 컨테이너 포트인 8005 사용

  # 시스템 메트릭 수집 (node-exporter)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:8100']